### ISSUE TITLE
4.36.03 broken - int to str

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-X#6]
get this error message:
Traceback (most recent call last):
  File "gam.py", line 23964, in ProcessGAMCommand
  File "gam.py", line 3178, in SetGlobalVariables
  File "gam.py", line 2950, in _getCfgInteger
  File "gam.py", line 2865, in _stripStringQuotes
  File "gam.py", line 2862, in _stringInQuotes
AttributeError: 'int' object has no attribute 'startswith'

This seems to help though:
  def _stringInQuotes(value):
    value = str(value)
    return (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'"))

**Comment by taers232c** [comment]
Mattias,

Thanks: https://github.com/taers232c/GAMADV-X/releases/tag/4.36.04

Ross

--
ross.scroggs@gmail.com
